name = "mocha_tc/converter"
version = "0.1.0"
description = "the client object converters for the mocha project"
authors = ["Primiti_ve", "Ice"]
license = "MIT"

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dependencies]
logger = { workspace = "mocha_tc/logger", version = "^" }
utils = { workspace = "mocha_tc/utils", version = "^" }
types = { workspace = "mocha_tc/types", version = "^" }